<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyVersion>2023.7.18.1</AssemblyVersion>
    <StartupObject>BackupAssistant.App</StartupObject>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
    <Authors>Darryl Eychner</Authors>
    <Company>Anaheim Electronics</Company>
    <Copyright>Copyright © Darryl Eychner 2023</Copyright>
    <FileVersion>2023.7.18.1</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;WFAC010</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;WFAC010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="System.IO.Abstractions" Version="19.2.29" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="ViewModels\MainWindowViewModel.*.cs">
      <DependentUpon>MainWindowViewModel.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
